# Generated by Django 4.1.7 on 2023-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spelsberg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(default='Ключевые слова', max_length=200),
        ),
    ]
